version: '3.8'

services:

    server:
        build:
            context: .
            dockerfile: docker/Dockerfile
        command: uvicorn src.homework.main:app --host 0.0.0.0 --port 8000 --reload
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - REDIS_DB=redis
        ports:
            - "8000:8000"
        networks:
          - app_network

    worker:
        build:
            context: .
            dockerfile: docker/Dockerfile
        command: celery -A src.homework.celery worker --loglevel=info
        environment:
          - CELERY_BROKER_URL=redis://redis:6379/0
          - CELERY_RESULT_BACKEND=redis://redis:6379/0
          - REDIS_DB=redis
        depends_on:
          - server
          - redis
        networks:
          - app_network

    redis:
        image: redis:7
        networks:
          - app_network

networks:
    app_network: